version: '3'
services:
  api:
    build: .
    command: sh -c "cd /home/node/app npm install && npm start"
    depends_on:
      - mongo
    ports:
      - "3000:3000"
    volumes:
      - .:/home/node/app
  mongo:
    image: mongo
    depends_on:
      - mongoAdminInterface
    ports:
      - "27017:27017"
  mongoAdminInterface:
    image: mongo-express
    ports:
      - "8081:8081"