before_script: cd fitness_tracker_api
language: node_js
node_js:
- lts/*
deploy:
  provider: heroku
  api_key:
    secure: JlXNSPsjrXj87DJfJ2+FKQN2InKEt5Do/UnBUTk3LaLp3/r2p/HqwD5eSoSodN/geInuXsvt9S9zj/fYRaIl2Lj9A7b3yyH6JpcBRd55hcmfqb5SMKWVsANfuPVl+Uv4qlorrTWgvwSDfIOVMzKb990POP87vfjTuWrcPM0N9F3oHeZ0BRrDb7wP1/79gX4DhSjf1W58wHF8NBBoQfeHiCf2BUHwHJElfL9BlulJB/0v3xN+OELfzqsyz24vXlB3RWrXg67I2Y305w1+TH8DuD2gjCuHAOVUMsBHMz4aq9ge4O1GpUbaXHV2vM4iMQWoa+S/mN3Mq3p7gZrmgqRhHC32+cFL+WC8aBqYYIm8XVEgQBeU0T/UErM07x9dMxfGmYRzGoqB0OsNO17dv2i+VMOTMs9IhOaF8yDaMeYl4t7EGkF21r8T7W7vIKhVT4vZj8DNLNTh5i/YDdzuqzZ7xOEiHa6gawU6ZIS08yg2nR+D/WZcwIME1oRU2r05yO0vSdk7emxMR1fKwC0mXqk8OYkpx43KJIY77mtHA9CBgfX11/rcMMQxNzIK52dETz3K8veCgB3d3lUPe1YRSvjttktd5JM6r2zqB2gllU15B5BqflbhPJhy/6/5BoFgNRASY643u1wHDSiCSpjX1CitfP93U43r0JUgqrnwIAoUDN8=